### ISSUE TITLE
Solution to Q1

### ISSUE THREAD

**Issue by Mandraxed** [widefox/widefox-python-papers#1]
# My first solution relies on slices. It requires 11 lines of code and gives the required output for a 5 element list.

a = [1, 3, 4, 8, 2]
print(a[0], "+", a[1], "=", a[0] + a[1])
print(a[0], "+", a[2], "=", a[0] + a[2])
print(a[0], "+", a[3], "=", a[0] + a[3])
print(a[0], "+", a[4], "=", a[0] + a[4])
print(a[1], "+", a[2], "=", a[1] + a[2])
print(a[1], "+", a[3], "=", a[1] + a[3])
print(a[1], "+", a[4], "=", a[1] + a[4])
print(a[2], "+", a[3], "=", a[2] + a[3])
print(a[2], "+", a[4], "=", a[2] + a[4])
print(a[3], "+", a[4], "=", a[3] + a[4])
# Your method is plainly better, requiring only 5 lines of code to handle lists of any length. However it throws an indentation error I could not resolve.

'''a = [1, 3, 4, 8, 2]
def addList(a):
    for i in range(0, len(a)-1):
        for j in range(i+1, len(a)):
            print('{}+{}={}'.format(a[i], a[j], a[i] + a[j]))'''

**Comment by widefox** [comment]
You've lost all the whitespace. Looks like you haven't copied the code correctly. Best to use the raw to preserve whitespace.
